-- TABELA DE TCAMPANHA

CREATE TABLE TCAMPANHA (
	codcamp BIGINT(20) PRIMARY KEY AUTO_INCREMENT,	
	nomcamp VARCHAR(150) NOT NULL,
	codtimcor BIGINT(20) NULL,
	dtvig DATE NOT NULL,	
	UNIQUE KEY (codcamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

